### PR TITLE
Add Code of Conduct to repo

### PR DESCRIPTION
**Pull request by margaretkennedy**
This file should have been included in the initial setup.

### CODE REVIEW

**Comment by margaretkennedy** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by margaretkennedy** [comment]
Recheck

**Comment by margaretkennedy** [comment]
***I have read the CLA Document and I hereby sign the CLA***

**Review by chipkent — APPROVED** [review]

**Comment by chipkent** [comment]
recheck

**Comment by margaretkennedy** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by margaretkennedy** [comment]
recheck

**Pull request closed without merging**
